
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 16 17:01:15 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LOGAND = 31;
  public static final int LBRACKET = 34;
  public static final int CHAR = 42;
  public static final int CONST = 3;
  public static final int EQUALS = 24;
  public static final int SEMI = 38;
  public static final int LPAREN = 36;
  public static final int GREATER = 27;
  public static final int CONTINUE = 13;
  public static final int LESS = 29;
  public static final int FOR = 14;
  public static final int MINUS = 20;
  public static final int RPAREN = 37;
  public static final int RANGE = 9;
  public static final int IN = 15;
  public static final int BOOL = 41;
  public static final int COMMA = 39;
  public static final int INC = 17;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int ASSIGN = 16;
  public static final int LESSEQ = 28;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int RBRACKET = 35;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int NUMBER = 40;
  public static final int IDENT = 43;
  public static final int BREAK = 12;
  public static final int VOID = 4;
  public static final int MODULE = 23;
  public static final int LBRACE = 32;
  public static final int ELSE = 11;
  public static final int READ = 5;
  public static final int NOTEQUALS = 25;
  public static final int LOGOR = 30;
  public static final int RBRACE = 33;
  public static final int PROG = 2;
  public static final int GREATEREQ = 26;
  public static final int DEC = 18;
  public static final int PRINT = 6;
}

