
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 11 14:01:07 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 5;
  public static final int IDENT = 30;
  public static final int PLUS = 13;
  public static final int RANGE = 9;
  public static final int RPAREN = 23;
  public static final int RBRACE = 19;
  public static final int CHAR = 29;
  public static final int SEMI = 24;
  public static final int RETURN = 8;
  public static final int COLON = 26;
  public static final int LPAREN = 22;
  public static final int LBRACKET = 20;
  public static final int LBRACE = 18;
  public static final int RBRACKET = 21;
  public static final int INC = 11;
  public static final int COMMA = 25;
  public static final int NUMBER = 27;
  public static final int MODULE = 17;
  public static final int EOF = 0;
  public static final int DIV = 16;
  public static final int PROG = 2;
  public static final int DEC = 12;
  public static final int MINUS = 14;
  public static final int CONST = 3;
  public static final int PRINT = 6;
  public static final int error = 1;
  public static final int ASSIGN = 10;
  public static final int NEW = 7;
  public static final int BOOL = 28;
  public static final int MUL = 15;
  public static final int VOID = 4;
}

