
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 08 21:03:20 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 5;
  public static final int IDENT = 29;
  public static final int PLUS = 12;
  public static final int RPAREN = 22;
  public static final int RBRACE = 18;
  public static final int CHAR = 28;
  public static final int SEMI = 23;
  public static final int RETURN = 8;
  public static final int COLON = 25;
  public static final int LPAREN = 21;
  public static final int LBRACKET = 19;
  public static final int LBRACE = 17;
  public static final int RBRACKET = 20;
  public static final int INC = 10;
  public static final int COMMA = 24;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int MODULE = 16;
  public static final int DIV = 15;
  public static final int PROG = 2;
  public static final int DEC = 11;
  public static final int MINUS = 13;
  public static final int CONST = 3;
  public static final int PRINT = 6;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int NEW = 7;
  public static final int BOOL = 27;
  public static final int MUL = 14;
  public static final int VOID = 4;
}

